/**
 * Generated by @openapi-codegen
 *
 * @version 0.1.0
 */
export type BodyLoginTokenPost = {
  grant_type?: string | null
  username: string
  password: string
  /**
   * @default
   */
  scope?: string
  client_id?: string | null
  client_secret?: string | null
}

export type BodySignupSignupPost = {
  username: string
  email: string
  full_name: string
  password: string
}

/**
 * Represents a Car record
 */
export type Car = {
  id: number
  car_model?: CarModel | null
  car_model_name: string
  year: number
  country: string
  city: string
  price: number
}

/**
 * Represents a CarBrand record
 */
export type CarBrand = {
  name: string
  CarModel?: CarModel[] | null
}

/**
 * Represents a CarModel record
 */
export type CarModel = {
  name: string
  brand_name: string
  image_name: string
  horse_power: number
  fuel_type: string
  fuel_economy: number
  brand?: CarBrand | null
  image?: Image | null
  Car?: Car[] | null
}

export type HTTPValidationError = {
  detail?: ValidationError[]
}

/**
 * Represents a Image record
 */
export type Image = {
  name: string
  /**
   * @format byte
   */
  data: string
  CarModel?: CarModel[] | null
}

/**
 * Represents a Token record
 */
export type Token = {
  access_token: string
  token_type: string
}

/**
 * Represents a User record
 */
export type User = {
  username: string
  email: string
  full_name: string
  hashed_password: string
}

export type ValidationError = {
  loc: (string | number)[]
  msg: string
  type: string
}
